enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

[YouTube-Divyaa]
enabled = true
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
rv-brand = "Morphe Divyaa"
build-mode = "apk"
excluded-patches = "'Change form factor' 'Spoof app version' 'Alternative thumbnails' 'Enable debugging' 'Spoof device dimensions' 'Disable sign in to TV popup' 'Spoof video streams' 'Hide timestamp' 'Check watch history domain name resolution'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
